default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5433
  username: postgres
  password: 123456
  pool: 5

development:
  <<: *default
  database: ecommerce_api_development

test:
  <<: *default
  database: ecommerce_api_test

production:
  <<: *default
  database: ecommerce_api_production
